### ISSUE TITLE
doesn't work with chromium 78

### ISSUE THREAD

**Issue by zaza42** [ugetdm/uget-integrator#80]
With Chromium 78.0.3904.97: 
```
Traceback (most recent call last):
  File "/usr/bin/uget-integrator", line 224, in <module>
    read_message()
  File "/usr/bin/uget-integrator", line 180, in read_message
    referer = data['Referer']
KeyError: 'Referer'
Traceback (most recent call last):
  File "/usr/bin/uget-integrator", line 224, in <module>
    read_message()
  File "/usr/bin/uget-integrator", line 180, in read_message
    referer = data['Referer']
KeyError: 'Referer'

```

**Comment by zaza42** [comment]
Forget it, now  works. Can't reproduce.
